#!/bin/bash
configName=$1
if [ -e "/var/run/"$configName".pid" ]
then
    kill -0 `cat /var/run/$configName.pid`
    if [ $? -eq 0 ]
    then
        echo Program is already running
	exit 0
    fi
fi

./ItBotSpawner.py config/$configName > /var/log/$configName"Log" &
echo $! > /var/run/$configName.pid